services:
  flask-api:
    build: TubeFetch.api/.
    container_name: TubeFetch.api
    ports:
      - "5000:5000"
    volumes:
      - ./songs:/usr/src/app/songs
    env_file:
      - .env
    restart: unless-stopped
  angular-frontend:
    build: TubeFetch.frontend/.
    container_name: TubeFetch.frontend
    ports:
      - "4201:4200"
    restart: unless-stopped

